version: '3.8'

services:
  api-db:
    container_name: api-db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test-db
    networks:
      - internal

  api:
    container_name: api
    build:
      context: .
    expose:
      - 8080
    networks:
      - internal



networks:
  internal:
    driver: bridge

volumes:
  postgres: