app:
  port: 8080
  env: production

db:
  user: postgres
  password: pass
  host: localhost
  port: 5434
  name: test-db

token:
  access: "skdjnfksdjskdjfnsk"
  refresh: "kwjernfkwejnfkwe"
  access_expire: 10 # 10 minutes
  refresh_expire: 20 # 20 minutes

redis:
  host: localhost
  port: 6379