basePath: /api/v1
definitions:
  handlers.Data:
    type: object
  handlers.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  handlers.RegisterResponse:
    properties:
      data:
        $ref: '#/definitions/handlers.Data'
      status:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: Сервер с базовой регистрацией в приложении через Bearer Token
  title: Swagger Example API
  version: "1.0"
paths:
  /users/:
    post:
      consumes:
      - application/json
      description: Proceed registration on the service using email, username, password
      parameters:
      - description: Request input struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.RegisterResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.RegisterResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RegisterResponse'
      security:
      - Bearer: []
      summary: Create new user
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
